![nn_architecture](media/nn_architecture.png)
![matrix_dims](media/matrix_dims.png)

In [24]:
import numpy as np
D = 728 # this would be mnist data dimension
K = 128 # hidden units first layer
C = 10 # number of classes
label = np.zeros(C)
class_index = 4
label[class_index] = 1

ReLU = lambda x: np.maximum(0, x)
def softmax(a):
    """
    compute softmax values for each element in a
    """
    if isinstance(a, list): a = np.array(a)
    exp_a = np.exp(a - np.max(a)) # minus max to stop overflows
    return exp_a / np.sum(exp_a)

def cross_entropy(y, pred):
    """
    return cross entropy value
    """
    if isinstance(y, list): y = np.array(y)
    if isinstance(pred, list): pred = np.array(pred)
    return - np.sum(np.multiply(y, np.log(pred)))
    

In [25]:
a = [0.2, 3.4, 4.0]
print(softmax(a))
print(cross_entropy([0, 0, 1], softmax(a)))

[0.01423818 0.34929849 0.63646334]
0.4518284619860037


In [35]:
# input 
x = np.random.randn(D, 1) * 0.01

# first layer
W = np.random.randn(K, D) * 0.01
b1 = np.random.randn(K, 1) * 0.01
z = W @ x + b1
h = ReLU(z)

# output layer
U = np.random.randn(C, K) * 0.01
b2 = np.random.randn(C, 1) * 0.01
a = U @ h + b2
print(softmax(a))
print(label)
loss = cross_entropy(label, softmax(a))
print(loss)




[[0.09861191]
 [0.09851508]
 [0.10159214]
 [0.10069832]
 [0.10162056]
 [0.10068797]
 [0.09890214]
 [0.09998248]
 [0.09806023]
 [0.10132917]]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
23.026701563468293
